#!/usr/bin/perl

#! /bin/perl

# pt-what: This tool will tell you which percona tool you can use for your task of choice.
# Version 2.1
# By Kedar Vaijanapurkar @ http://kedar.nitty-witty.com/blog
# MIT License
# ToDo: improvbe the task list

use strict;
use warnings;

my %tools = (
    "pt-archiver" => "Moves data from online tables to archive storage, backup data, archive data, archive and backup",
    "pt-config-diff" => "Compares the configuration of two servers, configuration comparison, global variables comparison",
    "pt-deadlock-logger" => "Monitors and logs deadlocks, save deadlocks, monitor deadlock, deadlock monitor",
    "pt-diskstats" => "Shows disk usage by table and index",
    "pt-duplicate-key-checker" => "Checks for duplicate keys in a table",
    "pt-fifo-split" => "Splits a FIFO file into multiple files",
    "pt-find" => "Searches for patterns in files",
    "pt-fingerprint" => "Shows the fingerprints of queries",
    "pt-flush-status" => "Shows the status of active and queued flushes",
    "pt-fk-error-logger" => "Monitors and logs foreign key errors",
    "pt-heartbeat" => "Creates a timestamp in a table",
    "pt-index-usage" => "Shows index usage statistics",
    "pt-kill" => "Kills queries",
    "pt-log-player" => "Replays queries from a log file",
    "pt-mext" => "Merges the contents of two tables",
    "pt-mongodb-query-digest" => "Analyzes MongoDB query performance",
    "pt-mysql-summary" => "Summarizes performance metrics for MySQL servers, database summary, MySQL Summary, ",
    "pt-online-schema-change" => "Performs online schema changes, dummy alter, almost zero downtime alter, no lock alter, table alter,fragmentation, disk free,defragment",
    "pt-opus" => "Shows the opcodes of queries",
    "pt-pmp" => "Manages a pool of MySQL servers",
    "pt-query-digest" => "Analyzes MySQL query performance",
    "pt-show-grants" => "Shows grants for all users",
    "pt-sift" => "Analyses a MySQL slow query log",
    "pt-slave-delay" => "Sets the replication delay for a slave server",
    "pt-slave-find" => "Finds the most lagging slave",
    "pt-slave-restart" => "Restarts a slave server",
    "pt-stalk" => "Watches for and diagnoses replication problems",
    "pt-summary" => "Summarizes information about the system and queries",
    "pt-table-checksum" => "Checks the replication consistency of tables, table checksum, ",
    "pt-table-sync" => "Synchronizes the data of two tables",
    "pt-table-usage" => "Shows table usage statistics",
    "pt-upgrade" => "Upgrade, MySQL Upgrade",
    "pt-variable-advisor" => "Advises on the use of MySQL system variables",
    "pt-visual-explain" => "Visualizes EXPLAIN output"
);

sub show_random_tool {
    my @keys = keys %tools;
    my $random_tool = $keys[rand @keys];
    print "FYI: The '$random_tool' can be used for: $tools{$random_tool}\n";
}

sub help {
    print "Usage: pt-what <task>\n";
    print "Search for Percona tools that can help with the specified task.\n\n";
    print "Options:\n";
    print "  task         Task to search for Percona tools for\n";
    print "  -h, --help   Show this help message\n";
    exit;
}


my @tasks = @ARGV or help();

if($tasks[0] eq "-h" || $tasks[0] eq "--help"){
    help();
}

if (!@tasks) {
    print "Error: No task specified.\n";
    help();
    &show_random_tool;
    exit 0;
}

print "\nPercona tools that may assist you with '@tasks' task:\n";
print "-------------------------------------------------\n";

my %matching_tools;

foreach my $task (@tasks) {
    foreach my $tool (keys %tools) {
        if ($tools{$tool} =~ /$task/i) {
            $matching_tools{$tool}++;
        }
    }
}

my @sorted_tools = sort {$matching_tools{$b} <=> $matching_tools{$a}} keys %matching_tools;

foreach my $tool (@sorted_tools) {
    print "* $tool\n";
}

if(!@sorted_tools) {
    print "No matching tools found for the task '@tasks'\n\n";
    &show_random_tool;
} else {
    print "\nTo download above tools use the following command:\n";
    print "wget percona.com/get/[TOOLNAME] && chmod +x [TOOLNAME]\n";
    print "Install Percona Toolkit: https://docs.percona.com/percona-toolkit/installation.html\n"
}
